on:
  workflow_dispatch:
    inputs:
      nonstandard:
        description: 'Use nonstandard GHCR token'
        required: false
        default: 'false'
# We need actions/write if we want to do a GH App, and we need
# packages/write to push to ghcr.io with GITHUB_TOKEN
permissions:
  actions: write
  contents: read
  packages: write
  statuses: read

jobs:
  login:
    runs-on: ubuntu-latest
    env:
      nonstandard: ${{ github.event.inputs.nonstandard }}

    steps:
      - name: dump environment
        run: |
          env
          if [ "${nonstandard}" = "false" ]; then
              echo "Nonstandard is false"
          else
              echo "Nonstandard is true"
          fi

      - name: login
        uses: lsst-sqre/multi-repository-login@v1
        with:
          images: ghcr.io/${{ github.repository }}
          use-nonstandard-ghcr-token: ${{ github.events.inputs.nonstandard == 'false' && false || true }}
          GHCR_PUSH_TOKEN: ${{ secrets.GHCR_PUSH_TOKEN }}
